######################################################
# Licensed Materials - Property of HCL Technologies
#  HCL Commerce
#  (C) Copyright HCL Technologies Limited 1996, 2020
######################################################
{{- if and .Values.tsDb.enabled (ne .Values.common.environmentType "share") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.common.tenant }}{{ .Values.common.environmentName}}{{ .Values.common.environmentType }}db
  namespace: {{ .Release.Namespace }}
  labels:
    app: HCL-Commerce
    chart: {{ .Chart.Name }}-{{ .Chart.Version}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }} 
spec:
  type: NodePort
  ports:
  - port: 50000
    name: dbport
  selector:
    component: {{ .Values.common.tenant }}{{ .Values.common.environmentName}}{{ .Values.common.environmentType }}db
{{- end -}}