######################################################
# Licensed Materials - Property of HCL Technologies
#  HCL Commerce
#  (C) Copyright HCL Technologies Limited 1996, 2020
######################################################
{{- if ne .Values.common.environmentType "share" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.common.tenant }}{{ .Values.common.environmentName}}{{ .Values.common.environmentType }}{{.Values.tsWeb.name}}
  labels:
    app: HCL-Commerce
    chart: {{ .Chart.Name }}-{{ .Chart.Version}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ .Values.common.tenant }}{{ .Values.common.environmentName}}{{ .Values.common.environmentType }}{{.Values.tsWeb.name}}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.common.localStoreEnabled }}
    cloud.google.com/app-protocols: '{"web443":"HTTPS","cmc8000":"HTTPS","acc8001":"HTTPS","admin8002":"HTTPS","org8004":"HTTPS"}'
    {{- else }}
    cloud.google.com/app-protocols: '{"cmc8000":"HTTPS","acc8001":"HTTPS","admin8002":"HTTPS","org8004":"HTTPS"}'
    {{- end }}
spec:
  type: NodePort
  ports:
  {{- if .Values.common.localStoreEnabled }}
  - port: 443
    name: web443
  {{- end }}
  - port: 8000
    name: cmc8000
  - port: 8001
    name: acc8001
  - port: 8002
    name: admin8002
  - port: 8004
    name: org8004
  selector:
    component: {{ .Values.common.tenant }}{{ .Values.common.environmentName}}{{ .Values.common.environmentType }}{{.Values.tsWeb.name}}
{{- end }}